spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.myvibereader: INFO
